import { languages, type Grammar } from "prism-code-editor/prism";

const mettaKeywords = [
  "if",
  "if-error",
  "if-equal",
  "==",
  "let",
  "not",
  "else",
  "case",
  "then",
  "while",
  "for",
  "def",
  "return",
  "and",
  "or",
  "empty",
  "match",
  "println",
  "trace",
  "assertEqualToResult",
  "car-atom",
  "collapse",
  "superpose",
  "bind",
  "import",
  "add-reduct",
  "pragma",
  "remove-atom",
  "cdr-atom",
  "cons-atom",
  "new-space",
  "quote",
  "assertEqual",
  "add-atom",
  "get-type",
  "get-metatype",
  "mod-space",
  "unify",
  "Nil",
  "True",
  "False",
  "Bool",
  "Number",
  "$_",
  "&self",
  "pow-math",
  "sqrt-math",
  "abs-math",
  "log-math",
  "trunc-math",
  "ceil-math",
  "floor-math",
  "round-math",
  "sin-math",
  "asin-math",
  "cos-math",
  "acos-math",
  "tan-math",
  "atan-math",
  "isnan-math",
  "isinf-math",
  "PI",
  "EXP",
  "print-mods",
  "register-module",
  "git-module",
  "random-int",
  "random-float",
  "flip",
  "new-state",
  "change-state",
  "get-state",
  "get-type-space",
  "min-atom",
  "max-atom",
  "size-atom",
  "index-atom",
  "unique-atom",
  "subtraction-atom",
  "intersection-atom",
  "union-atom",
  "=alpha",
  "assertAlphaEqualToResult",
  "assertAlphaEqual",
  "filter-atom",
  "map-atom",
  "foldl-atom",
  "unquote",
  "noreduce-eq",
  "first-from-pair",
  "match-type-or",
  "ERROR",
];

const escapeRegExp = (value: string) =>
  value.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");

export const mettaLanguage: Grammar = {
  comment: /;.*/,
  string: /"(?:\\.|[^"\\])*"/,
  number: /(?:\b\d+(?:\.\d+)?|\B-\d+(?:\.\d+)?)/,
  keyword: new RegExp(
    `(?:${mettaKeywords.map(escapeRegExp).join("|")})(?=$|[\\s(){}[\\]])`
  ),
  variable: /\$[a-zA-Z0-9_-]+/,
  operator: /[+\-*/=><%]+/,
  punctuation: /[(){}[\]]/,
  symbol: /[^\s(){}[\]";]+/,
};

languages.metta = mettaLanguage;
